### ISSUE TITLE
How do you edit starbound_server.config?

### ISSUE THREAD

**Issue by woeisme** [Didstopia/starbound-server#7]
The container image seems to overwrite starbound_server.config at each restart, how do we edit the file but retain changes on restarts?

**Comment by Dids** [comment]
Did you set up persistence with the two volumes or bind mounts as seen here?
https://github.com/Didstopia/starbound-server/blob/master/docker-compose.yaml

**Comment by woeisme** [comment]
I started with the default two volumes in my docker-compose.yaml 

Previous to this I was having to shell into the container via `docker exec -it  starbound bash`
and hand modifying starbound-server.config.

Last night I ran `docker restart starbound` after added another player and it reset the config back to default template.

What's the preferred method for modifying starbound_server.config and retaining those changes between restarts?

Eventually I'd like to switch this setup to bind mounts as that would help with being able to modify files even when the container is stopped. I'll attach my docker-compose.yaml below :

```
services:
  starbound-server:
    image: didstopia/starbound-server:latest
    container_name: starbound
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    ports:
      - "21025:21025/tcp"
    volumes:
      - starbound-data:/steamcmd/starbound
      - starbound-steam:/app/.steam:cached
    restart: unless-stopped
#    volumes:
#      - /data/starbound/steamcmd/starbound:/starbound-data
#      - /data/starbound/app/.steam:/starbound-steam
#    volumes:
#      - /home/BLANKED/starbound-server/starbound-data:/steamcmd/starbound:cached
#      - /home/BLANKED/starbound-server/starbound-steam:/app/.steam:cached
volumes:
  starbound-data:
  starbound-steam:
```
